<a href="https://colab.research.google.com/github/Gangadhar24377/VQGAN-training-model_Images/blob/main/Copy_of_VqGan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/RohitMidha23/Image-Directory-to-CSV

fatal: destination path 'Image-Directory-to-CSV' already exists and is not an empty directory.


Converting the dataset into .csv file as the input is file 

In [ ]:
from PIL import Image
import numpy as np
import sys
import os
import csv

# default format can be changed as needed
def createFileList(myDir, formats=['.jpg', '.jpeg', '.png']):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            for format in formats:
                if name.endswith(format):
                    fullName = os.path.join(root, name)
                    fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('/content/Images')

for file in myFileList:
    try:
        print(file)
        img_file = Image.open(file)
        # img_file.show()

        # get original image parameters...
        width, height = img_file.size
        format = img_file.format
        mode = img_file.mode

        # Make image Greyscale
        img_grey = img_file.convert('L')
        #img_grey.save('result.png')
        #img_grey.show()

        # Save Greyscale values
        value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
        value = value.flatten()
        print(value)
        with open("/content/dataset.csv", 'a') as f:
            writer = csv.writer(f)
            writer.writerow(value)
    except OSError as e:
        print(f"Error: {e}")


/content/Images
/content/Images/1 (15).png
[238 238 238 ... 105 103 105]


<ipython-input-2-260fc523d5ce>:39: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))


/content/Images/1 (33).jpg
[147 147 147 ...  36  36  36]
/content/Images/1 (17).png
[107 107 109 ...  97  96  96]
/content/Images/1 (55).jpeg
[176 176 176 ... 163 162 163]
/content/Images/1 (14).jpg
[222 222 222 ...   6   6   7]
/content/Images/1 (99).jpg
[24 24 25 ... 27 27 27]
/content/Images/1 (70).jpg
[218 219 220 ... 215 217 217]
/content/Images/1 (17).jpeg
[197 197 197 ... 189 189 190]
/content/Images/1 (54).png
[105 105 105 ... 255 255 255]
/content/Images/1 (79).jpeg
[ 86  85  81 ... 172 172 172]
/content/Images/1 (12).png
[52 52 52 ... 52 52 52]
/content/Images/1 (72).png
[68 70 71 ... 67 65 66]
/content/Images/1 (85).jpg
[ 92  90  87 ... 185 183 185]
/content/Images/1 (25).jpg
[ 7  8 10 ... 28 28 28]
/content/Images/1 (57).jpeg
[193 193 194 ... 115 113 111]
/content/Images/1 (23).png
[126 124 122 ... 178 178 178]
/content/Images/1 (50).png
[126 124 122 ... 178 178 178]
/content/Images/1 (17).jpg
[205 205 205 ...  44  42  42]
/content/Images/1 (31).png
[225 225 225 ...  99  99

/usr/local/lib/python3.9/dist-packages/PIL/Image.py:975: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


[ 97  97  97 ... 231 238 238]
/content/Images/1 (6).jpeg
[32 30 32 ...  1  1  1]
/content/Images/1 (86).jpg
[162 162 162 ... 118 119 119]
/content/Images/1 (2).png
[126 124 122 ... 178 178 178]
/content/Images/1 (78).png
[255 255 255 ... 255 255 255]
/content/Images/1 (1).jpeg
[ 0  0  0 ... 14 13 13]
/content/Images/1 (16).jpeg
[ 86  85  81 ... 172 172 172]
/content/Images/1 (45).jpg
[71 79 76 ... 15 17 22]
/content/Images/1 (43).png
[126 124 122 ... 178 178 178]
/content/Images/1 (55).png
[105 105 105 ... 255 255 255]
/content/Images/1 (38).jpg
[149 149 150 ... 249 250 250]
/content/Images/1 (30).jpeg
[  2   0   3 ... 247 246 246]
/content/Images/1 (74).jpg
[ 46  45  47 ... 199 200 199]
/content/Images/1 (63).jpeg
[208 209 210 ...   7   6  10]
/content/Images/1 (9).png
[161 161 160 ...  90  87  82]
/content/Images/1 (34).jpg
[1 1 1 ... 5 5 5]
/content/Images/1 (39).png
[ 69  66  73 ... 141 144 136]
/content/Images/1 (10).jpg
[198 198 198 ... 178 178 178]
/content/Images/1 (75).png
[ 8

In [ ]:
!pip install git+https://github.com/patil-suraj/vqgan-jax.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/patil-suraj/vqgan-jax.git to /tmp/pip-req-build-6jdfteea
  Running command git clone --filter=blob:none --quiet https://github.com/patil-suraj/vqgan-jax.git /tmp/pip-req-build-6jdfteea
  Resolved https://github.com/patil-suraj/vqgan-jax.git to commit 10ef240f8ace869e437f3c32d14898f61512db12
  Preparing metadata (setup.py) ... done


In [ ]:
# VQGAN-JAX - pmap encoding HowTo

import numpy as np

# For data loading
import torch
import torchvision.transforms.functional as TF
from torch.utils.data import Dataset, DataLoader
from torchvision.datasets.folder import default_loader
from torchvision.transforms import InterpolationMode

# For data saving
from pathlib import Path
import pandas as pd
from tqdm import tqdm

import jax
from jax import pmap

from vqgan_jax.modeling_flax_vqgan import VQModel


/usr/local/lib/python3.9/dist-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(


In [ ]:
## Params and arguments

# List of paths containing images to encode
image_list = '/sddata/dalle-mini/CC12M/10k.tsv'
output_tsv = 'output.tsv'                # Encoded results
batch_size = 64
num_workers = 4    # TPU v3-8s have 96 cores, so feel free to increase this number when necessary

# Load model

model = VQModel.from_pretrained("flax-community/vqgan_f16_16384", ignore_mismatched_sizes=True)

Some weights of VQModel were not initialized from the model checkpoint at flax-community/vqgan_f16_16384 and are newly initialized because the shapes did not match:
- ('decoder', 'mid', 'attn_1', 'norm', 'bias'): found shape (1, 1, 1, 512) in the checkpoint and (512,) in the model instantiated
- ('decoder', 'mid', 'attn_1', 'norm', 'scale'): found shape (1, 1, 1, 512) in the checkpoint and (512,) in the model instantiated
- ('decoder', 'mid', 'block_1', 'norm1', 'bias'): found shape (1, 1, 1, 512) in the checkpoint and (512,) in the model instantiated
- ('decoder', 'mid', 'block_1', 'norm1', 'scale'): found shape (1, 1, 1, 512) in the checkpoint and (512,) in the model instantiated
- ('decoder', 'mid', 'block_1', 'norm2', 'bias'): found shape (1, 1, 1, 512) in the checkpoint and (512,) in the model instantiated
- ('decoder', 'mid', 'block_1', 'norm2', 'scale'): found shape (1, 1, 1, 512) in the checkpoint and (512,) in the model instantiated
- ('decoder', 'mid', 'block_2', 'norm1', 'bi

In [ ]:
## Data Loading.

# Simple torch Dataset to load images from paths.
# You can use your own pipeline instead.
class ImageDataset(Dataset):
    def __init__(self, image_list_path: str, image_size: int, max_items=None):
        """
        :param image_list_path: Path to a file containing a list of all images. We assume absolute paths for now.
        :param image_size: Image size. Source images will be resized and center-cropped.
        :max_items: Limit dataset size for debugging
        """
        
        self.image_list = pd.read_csv(image_list_path, sep='\t', header=None)
        if max_items is not None: self.image_list = self.image_list[:max_items]
        self.image_size = image_size
        
        
    def __len__(self):
        return len(self.image_list)
    
    def _get_raw_image(self, i):
        image_path = Path(self.image_list.iloc[i][0])
        return default_loader(image_path)
    
    def resize_image(self, image):
        s = min(image.size)
        r = self.image_size / s
        s = (round(r * image.size[1]), round(r * image.size[0]))
        image = TF.resize(image, s, interpolation=InterpolationMode.LANCZOS)
        image = TF.center_crop(image, output_size = 2 * [self.image_size])
        image = np.expand_dims(np.array(image), axis=0)
        return image
    
    def __getitem__(self, i):
        image = self._get_raw_image(i)
        return self.resize_image(image)

In [ ]:
## Encoding

# Encoding function to be parallelized with `pmap`
# Note: images have to be square
def encode(model, batch):
    _, indices = model.encode(batch)
    return indices

In [ ]:
# Alternative: create a batch with num_tpus*batch_size and use `shard` to distribute.
def superbatch_generator(dataloader, num_tpus):
    iter_loader = iter(dataloader)
    for batch in iter_loader:
        superbatch = [batch.squeeze(1)]
        try:
            for _ in range(num_tpus-1):
                batch = next(iter_loader)
                if batch is None:
                    break
                # Skip incomplete last batch
                if batch.shape[0] == dataloader.batch_size:
                    superbatch.append(batch.squeeze(1))
        except StopIteration:
            pass
        superbatch = torch.stack(superbatch, axis=0)
        yield superbatch

def encode_dataset(dataset, batch_size=32):
    dataloader = DataLoader(dataset, batch_size=batch_size, num_workers=num_workers)
    superbatches = superbatch_generator(dataloader, num_tpus=jax.device_count())
    
    num_tpus = jax.device_count()
    dataloader = DataLoader(dataset, batch_size=batch_size, num_workers=num_workers)
    superbatches = superbatch_generator(dataloader, num_tpus=num_tpus)
    
    p_encoder = pmap(lambda batch: encode(model, batch))

    # Save each superbatch to avoid reallocation of buffers as we process them.
    # Keep the file open to prevent excessive file seeks.
    with open(output_tsv, "w") as file:
        iterations = len(dataset) // (batch_size * num_tpus)
        for n in tqdm(range(iterations)):
            superbatch = next(superbatches)
            encoded = p_encoder(superbatch.numpy())
            encoded = encoded.reshape(-1, encoded.shape[-1])

            # Extract paths from the dataset, save paths and encodings (as string)
            start_index = n * batch_size * num_tpus
            end_index = (n+1) * batch_size * num_tpus
            paths = dataset.image_list[start_index:end_index][0].values
            encoded_as_string = list(map(lambda item: np.array2string(item, separator=',', max_line_width=100, formatter={'int':lambda x: str(x)}), encoded))
            batch_df = pd.DataFrame.from_dict({"image_file": paths, "encoding": encoded_as_string})
            batch_df.to_csv(file, sep='\t', header=(n==0), index=None)
            
dataset = ImageDataset(image_list_path="/content/dataset.csv", image_size=256)
encoded_dataset = encode_dataset(dataset, batch_size=batch_size)